# -*- coding: utf-8 -*-
"""library system.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KzzwJYQ0vaS-W3J4lrxQYUprQ7G_FU9X
"""

data = {

'stud':
    {
     2001 : {'name': 'Sanket Gangwani'  , 'year': 'FY', 'degree': 'Automobile', 'books issued': 0},
     2002 : {'name': 'Dp Dubey'         , 'year': 'SY', 'degree': 'Automobile', 'books issued': 0},
     2003 : {'name': 'Nitin Chhabria'   , 'year': 'TY', 'degree': 'Cs'        , 'books issued': 0},
     2004 : {'name': 'Rahul Ramrakhyani', 'year': 'TY', 'degree': 'Cs'        , 'books issued': 0},
     2005 : {'name': 'Abhishek Said'    , 'year': 'FY', 'degree': 'Automobile', 'books issued': 0},
     2006 : {'name': 'Parth Sejpal'     , 'year': 'TY', 'degree': 'Mechanical', 'books issued': 0},
     2007 : {'name': 'Rahul Tejwani'    , 'year': 'SY', 'degree': 'Cs'        , 'books issued': 0},
     2008 : {'name': 'Ajay Malusare'    , 'year': 'SY', 'degree': 'Mechanical', 'books issued': 0},
     2009 : {'name': 'Jai Talreja'      , 'year': 'TY', 'degree': 'Cs'        , 'books issued': 0},
     2010 : {'name': 'Abhishek Jadhav'  , 'year': 'FY', 'degree': 'Automobile', 'books issued': 0}
    },


'book' :
    {
    'Romance':
            {
            1001:{'book_name': 'Jane Eyre'                        , 'author': 'Charollete Bronte'      , 'quantity': 5 , 'price': 100},
            1002:{'book_name': 'Pride and Prejudice'              , 'author': 'Jane Austen'            , 'quantity': 5 , 'price': 100},
            1003:{'book_name': 'Emma'                             , 'author': 'Jane Austen'            , 'quantity': 5 , 'price': 150}
            },

    'Autobiography':
            {
             1004:{'book_name': 'I Am Vidya'                      , 'author': 'Vidya'                  , 'quantity': 5 , 'price': 1400},
             1005:{'book_name': 'Mein Kampf'                      , 'author': 'Adolf Hitler'           , 'quantity': 5 , 'price': 450},
             1006:{'book_name': 'Me Hijra, Me Laxmi'              , 'author': 'Laxmi Narayan Tripathi' , 'quantity': 5 , 'price': 400}
            },

    'Tragedy':
            {
             1007: {'book_name': 'Tara'                           , 'author': 'Mahesh Dattani'          , 'quantity': 5 , 'price': 300},
             1008: {'book_name': 'Dance Like A Man'               , 'author': 'Mahesh Dattani'          , 'quantity': 5 , 'price': 100},
             1009: {'book_name': 'Macbeth'                        , 'author': 'Macbeth'                 , 'quantity': 5 , 'price': 100}
            },

    'Gothic':
            {
             1010: {'book_name': 'Frankenstein'                   , 'author': 'Mary Shelley'            , 'quantity': 5 , 'price': 250},
             1011: {'book_name': 'The Tell-Tale Heart'            , 'author': 'Edgar Allan Poe'         , 'quantity': 5 , 'price': 250}
            },

    'Epic' :
            {
             1012: {'book_name': 'Paradise Lost'                  , 'author': 'John Milton'             , 'quantity': 5 , 'price': 200},
             1013: {'book_name': 'Savitri: A Legend and a Symbol' , 'author': 'Aurobindo Ghosh'         , 'quantity': 5 , 'price': 350}
            }
    }
       }

from datetime import date
from datetime import timedelta

! mkdir Library_Data
stud_books = {}

roll_no = int(input('Enter your roll number: '))

if(roll_no in data['stud']):
    print('\nWelcome to the library '+data['stud'][roll_no]['name'])
    print('Please type "Issue" to issue a new book or "Return" to return the issued book\n')
    issue_or_return = input('Issue/Return: ').title()
    if(issue_or_return.title() == 'Issue'):
        has_issued = False
        if(data['stud'][roll_no]['books issued'] < 5):
            print()
            genre = input('Please mention what genre books you are looking for?: ').title()
            if(genre.title() in data['book']):
                print('\nFollowing are the books available in '+genre+' genre: ')
                for i in data['book']:
                    if(genre == i):
                        c = 1
                        for j in data['book'][i]:
                            print(str(c)+'. '+data['book'][i][j]['book_name']+' ('+data['book'][i][j]['author']+' )')
                            c+=1
                print('\nWould you like to issue any of the books mentioned above?\n')
                issue = input('Type "Yes" to issue or "No" to exit: ').title()
                if(issue.title() == 'Yes'):
                    book = input('Mention the name of the book you want to issue: ').title()
                    present = False
                    for i in data['book']:
                        for j in data['book'][i]:
                            if(book.title() == data['book'][i][j]['book_name'].title()):
                                present = True
                                if(data['stud'][roll_no]['name'] in stud_books):

                                    if(book.title() not in stud_books[data['stud'][roll_no]['name']]):
                                        if(data['book'][i][j]['quantity']>=1):
                                            data['book'][i][j]['quantity'] = data['book'][i][j]['quantity']-1
                                            issuedate = date.today()
                                            returndate = issuedate+timedelta(days=7)
                                            has_issued = True
                                            print()
                                            print('-'*60)
                                            print('You have successfully issued your book '+'"'+book+'"')
                                            print('-'*60)
                                            print('Date of issue is:',issuedate,'[YY-MM-DD]')
                                            print('Date of return is:',returndate,'[YY-MM-DD]')
                                            print('-'*60)
                                            for s in data['stud']:
                                                if(roll_no == s):
                                                    data['stud'][s]['books issued'] += 1
                                            if(has_issued == True):
                                                temp = {}
                                                nam = data['stud'][roll_no]['name']
                                                stud_books[nam][book] = {}
                                                stud_books[nam][book]['issue'] = str(issuedate)
                                                stud_books[nam][book]['return'] = str(returndate)
                                                stud_books.update(temp)

                                                txt = json.dumps(stud_books)
                                                fd = open('Library_Data/Lib_issued '+str(date.today())+'.json','w')
                                                fd.write(txt)
                                                fd.close()
                                        else:
                                            print('-'*60)
                                            print('No stocks are available for',book)
                                            print('-'*60)

                                    else:
                                        print()
                                        print('-'*60)
                                        print('Unable to issue')
                                        print("You have already issued a copy of "+book)
                                        print('-'*60)

                                elif(data['stud'][roll_no]['name'] not in stud_books):
                                    if(data['book'][i][j]['quantity']>=1):
                                        data['book'][i][j]['quantity'] = data['book'][i][j]['quantity']-1
                                        issuedate = date.today()
                                        returndate = issuedate+timedelta(days=7)
                                        has_issued = True
                                        print()
                                        print('-'*60)
                                        print('You have successfully issued your book '+'"'+book+'"')
                                        print('-'*60)
                                        print('Date of issue is:',issuedate,'[YY-MM-DD]')
                                        print('Date of return is:',returndate,'[YY-MM-DD]')
                                        print('-'*60)
                                        for s in data['stud']:
                                            if(roll_no == s):
                                                data['stud'][s]['books issued'] += 1
                                        if(has_issued == True):
                                            temp = {}
                                            nam = data['stud'][roll_no]['name']
                                            if(nam not in stud_books):
                                                temp[nam] = {}
                                                temp[nam][book] = {}
                                                temp[nam][book]['issue'] = str(issuedate)
                                                temp[nam][book]['return'] = str(returndate)
                                                stud_books.update(temp)
                                            else:
                                                stud_books[nam][book] = {}
                                                stud_books[nam][book]['issue'] = str(issuedate)
                                                stud_books[nam][book]['return'] = str(returndate)
                                                stud_books.update(temp)

                                            txt = json.dumps(stud_books)
                                            fd = open('Library_Data/Lib_issued '+str(date.today())+'.json','w')
                                            fd.write(txt)
                                            fd.close()
                                    else:
                                        print('-'*60)
                                        print('No stocks are available for',book)
                                        print('-'*60)

                    if(present == False):
                        print('-'*60)
                        print('Please provide valid name of the book')
                        print('-'*60)

                elif(issue.title() == 'No'):
                    print('-'*60)
                    print('Thank you for exploring our library')
                    print('-'*60)

                else:
                    print('\nPlease provide input as "Yes" or "No"')

            else:
                print('-'*70)
                print("Seems like we couldn't find any genre that matches your requirement")
                print('-'*70)

        else:
            print('-'*70)
            print("Oops! Looks like you have already issued 5 books")
            print('Please return some of the issued books in order to issue new.')
            print('-'*70)

    elif(issue_or_return.title() == 'Return'):
        if(data['stud'][roll_no]['name'] in stud_books):
            iss_book = input('Please mention name of the book that you are returning: ').title()
            if(iss_book not in stud_books[data['stud'][roll_no]['name']]):
                print('-'*70)
                print("We couldn't find "+iss_book+' book in your issued books')
                print('Please try again by entering valid details')
                print('-'*70)
            else:
                for i in data['book']:
                    for j in data['book'][i]:
                        if(iss_book.title() == data['book'][i][j]['book_name'].title()):
                            data['book'][i][j]['quantity'] = data['book'][i][j]['quantity']+1
                            print('-'*70)
                            print('You have successfulyy returned your issued book')
                            print('-'*70)
                            del stud_books[data['stud'][roll_no]['name']][iss_book]
                            for s in data['stud']:
                                if(roll_no == s):
else:
    print('-'*70)
    print('You are not registered with our data')
    print('-'*70)
    print('Type "Yes" to register or "No" to exit')
    register = input('Would you like to register?')
    if(register.title() == 'Yes'):
        print('\nProvide further details to register\n')
        roll_n = int(input('Enter your roll number: '))
        name = input('Enter your full name: ').title()
        year = input('Enter your year of study: ').upper()
        degree = input('Enter your degree: ').title()
        temp = {}
        temp['name']=name
        temp['year']=year
        temp['degree'] = degree
        temp['books issued'] = 0
        dct = {}
        dct[roll_n] = temp
        data['stud'].update(dct)
        print('-'*70)
        print('You are now registered with our system')
        print('Please login to access our library')
        print('-'*70)
    else:
        print('-'*70)
        print('Thank you for visiting our library')
        print('-'*70)